config/routes.rb
Rails.application.routes.draw do

  # Devise Routes / Authentication routes
  devise_for :contacts, path: 'contact_users', controllers: { passwords: 'contacts/passwords', sessions: 'contacts/sessions' }
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords', sessions: 'users/sessions' }
  namespace :users do
    resource :two_factor_authentication, controller: 'two_factor_authentication', only: [:new, :show, :create] do
      collection do
        get :resend_direct_otp
      end
    end
  end
  namespace :users do
    resources :tfa_phone_numbers, only: [:index, :new, :create, :destroy]
  end


  # Engine Routes
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'

  # Application Routes
  get 'authorize' => 'auth#gettoken'
  get 'mail/index'

  get 'home/index'
  get 'google_autication' => 'google_imap#authentication'
  get 'oauth2callback' => 'google_imap#callback'
  get 'get_access_code' => 'google_imap#get_access_code'

  get 'home/dashboard'
  resources :work_flows do
    collection do
      post 'builder'
      post 'action_builder'
    end
  end
  resources :companies do
    get 'logo_image'
    delete 'remove_logo'
  end
  resources :search
  resources :user_permissions
  namespace :contacts do
    root 'home#dashboard'
    resources :projects do
      member do
        get 'overview'
        get 'accept_contact_invitation'
        get 'project_details'
      end
      collection do
      end
      resources :messages do
        delete 'comment_delete'
      end
      resources :project_documents
    end
    # resources :messages
    resources :contacts do
      delete 'remove_image'
      patch 'upload_image'
      get 'new_image'
      patch 'phone_update'
      get 'company_edit'
      patch 'company_update'
      collection do
        patch 'client_update/:id', to: 'contacts#client_update', as: 'client_update'
      end
    end
    resources :tickets do
      member do
        get 'overview'
      end
      resources :messages do
        get 'reply_edit'
        patch 'reply_update'
        delete 'reply_delete'
      end
      resources :ticket_documents
    end
    #resources :ticket_documents
    resources :invoices
    resources :inventories
    resources :messages
    resources :directories do
      collection do
        delete :destroy_all
        get 'system_files'
      end
    end
    resources :documents do
      collection do
        delete :destroy_all
        get 'upload_document'
        get 'update_documents'
        get 'selected_documents'
      end
    end
    post 'uploadfiles'=>'documents#upload'
  end

  get 'contacts/dashboard' => 'contacts/home#dashboard'

  get 'settings/index'
  post 'uploadfiles'=>'documents#upload'

  resources :leads do
    resources :comments, only: [:create, :update,:index]
    #resources :tasks
    collection do
      delete 'destroy_all'
      get 'import_leads'
      post 'import_map'
      get 'assign_all', to: 'leads#new_assign_all'
      post 'assign_all'
    end
    member do
      get 'convert_client'
      get 'edit_summary'
    end
  end
  post 'import_file' => 'leads#import_file'
  get 'import_form' => 'leads#import_form'
  resources :contacts do
    collection do
      get 'check_email'
      get 'resend_invitation'
      get 'lead_contacts'
      get 'client_contacts'
      get 'vendor_contacts'
      delete 'destroy_all'
    end
  end

  resources :project_tasks
  get 'search_auto_complete_data_tasks' => 'project_tasks#search_auto_complete_data_tasks', :as => "search_auto_complete_data_tasks"
  resources :projects do
    collection do
      delete 'destroy_all'
      get 'user_list'
      get 'list'
      post 'send_project_invitaiton'
      get 'project_user_list'
    end
    member do
      get 'overview'
      get 'invite_for_project'
      get 'project_details'
      get 'accept_user_invitation'
    end
    resources :messages do
      delete 'comment_delete'
    end
    resources :project_documents
  end

  get 'project_communication_dashborad' => 'projects#project_communication_dashborad', as: :project_communication_dashborad
  get "back_to_project/:id" => "projects#back_to_project", as: :back_to_project

  resources :messages
  resources :tickets do
    collection do
      delete 'destroy_all'
      get 'contacts_list'
      get 'user_list'
      get 'list'
      post 'send_ticket_invitaiton'
      get 'ticket_user_list'
      get 'reports'
      post 'download_attachment', to: 'tickets#download_attachment', as: :download_attachment
    end
    member do
      get 'overview'
      get 'invite_for_ticket'
      get 'ticket_details'
    end
    resources :messages do
      delete 'comment_delete'
      get 'reply_edit'
      patch 'reply_update'
      delete 'reply_delete'
    end
    resources :ticket_documents
  end

  get 'autocomplete_data' => 'tickets#autocomplete_data', :as => "autocomplete_data_tickets"
  get 'back_to_ticket/:id' => 'tickets#back_to_ticket', as: :back_to_ticket


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#dashboard'
  resources :settings do
    collection do
      get 'module', as: :module
      get 'actions'
      get 'users_settings', as: :users
      get 'module_select'
      get 'email'
      get 'revoke_mail_access'
      resources :users do
        delete 'remove_image'
        get 'signature'
        patch 'update_signature'
        patch 'upload_image'

        get 'resend_invitation'
      end
      get 'new_image' => 'users#new_image'
      resources :roles
    end
  end
  resources :groups do
    collection do
      get :change_position
    end
  end
  resources :fields do
    collection do
      get :change_position
      patch :change_position_in_table
      patch :change_header_view
      patch :toggle_visible_in_table
    end
    member do
      patch :change_properties
    end
  end
  resources :field_picklist_values do
    collection do
      get :change_klass
      get :change_field
      get :change_position
    end
  end
  resources :custom_values
  get '/dashboard', to: 'home#dashboard'

  resources :clients do
    resources :comments, only: [:create,:update,:index]
    resources :inventory_associations, module: :clients, only: [:index] do
      collection do
        get :subcategories
        get :inventory_groups
        get :inventory_group
        get :inventory_groups_by_sku
        get :bulk_new
        post :bulk_create
      end
    end
    resources :shipments, module: :clients, only: [:new, :create] do
      get 'package_label/:id', to: 'shipments#package_label', as: :package_label
    end
    resources :employees, module: :clients do
      member do
        get 'feedback'
      end
    end
    collection do
      delete :destroy_all
      get 'import_clients'
      post 'import_map'
      get 'select_client'
      get 'status_board'
      post 'update_status_board'
      get 'department_details'
      get :client_by_merchant_id
    end
    post 'set'
    member do
      get 'edit_summary'
      get 'send_menu_approval_email'
      get 'send_menu_approval_sms'
      get 'logs'
    end
  end
  post 'import_file_client' => 'clients#import_file_client'
  get 'import_form_client' => 'clients#import_form_client'

  resources :vendors do
    member do
      get 'edit_summary'
    end
    collection do
      delete :destroy_all
    end
  end


  get 'page1', to: 'home#page1'
  get 'project_communication_dashborad1', to: 'home#project_communication_dashborad1'
  resources :module_numbers
  get 'page2', to: 'home#page2'
  get "get_module_name" => "module_numbers#get_module_name"
  get 'privacy', to: 'home#privacy'
  get 'view_map', to: 'home#view_map'

  resources :invoices do
    collection do
      delete :destroy_all
      get :inventories
      get :clients
    end
    get 'email'
    post 'email_create'
    get 'preview'
    get 'download'
    resource :payment, except: [:edit, :update, :destroy]
  end

  resources :directories do
    collection do
      delete 'destroy_all'
      get 'system_files'
    end
  end
  resources :documents do
    collection do
      delete :destroy_all
      get 'upload_document'
      get 'update_documents'
      get 'selected_documents'
    end
  end

  resources :tasks do
    collection do
      delete :destroy_all
    end
    post :mark_as_completed
  end
  get 'back_to_task/:id', to: 'tasks#back_to_task', as: :back_to_task

  resources :notes do
    collection do
      delete :destroy_all
    end
  end
  get 'back_to_note/:id', to: "notes#back_to_note", as: :back_to_note
  resources :roles
  resources :emails do
    post :reply
    collection do
      get :sent
      get :draft
      get :connect
      get :update_draft
      get :create_draft
      delete 'destroy_draft/:id', to: 'emails#destroy_draft', as: 'destroy_draft'
    end
  end

  namespace :purchase_order do
    resources :devices, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :products, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :versions, only: [:show, :create]
  end

  resources :inventory_groups do
    collection do
      patch :setup_inventory_versions
      delete :destroy_all
      get :subcategories_for_category
    end
  end

  # Category Management
  resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :subcategories, only: [:new, :edit, :create, :update, :destroy]

  resources :inventories do
    collection do
      delete :destroy_all
      get :import
      post :import_map
      put :update_inventory_column
      get :subcategories_for_data_list
      post :import_file
    end
    member do
      get :logs
    end
  end

  resources :stock_adjustments, except: %i[index show]
  resources :email_templetes do
    collection do

app/models/directory.rb
class Directory < ApplicationRecord
  # acts_as_paranoid
  audited
  default_scope { order(:name) }

  belongs_to :directoriable, polymorphic: true, optional: true
  # belongs_to :user, optional: true
  belongs_to :resourcable, polymorphic: true, optional: true
  # has_many :documents, dependent: :destroy
  has_many :directories, as: :directoriable, dependent: :destroy
  has_many :document_documentables, as: :documentable, dependent: :destroy
  has_many :documents, through: :document_documentables
  # accepts_nested_attributes_for :documents, reject_if: :all_blank, allow_destroy: true
  # accepts_nested_attributes_for :directories, reject_if: :all_blank, allow_destroy: true

  def get_directory
    Directory.find(self.directoriable_id).id
  end

  def directory_on_index(id)
    Directory.find(id).name
  end

end

app/controllers/contacts/directories_controller.rb
class Contacts::DirectoriesController < ApplicationController
  layout 'contacts'
  
  def new
    @directory = Directory.new(directoriable_type: params[:directoriable_type], directoriable_id: params[:directoriable_id])
  end


  def create
    @directory = Directory.new(directory_params.merge({ resourcable: current_contact}))
    if @directory.save
      flash[:success] = "Directory successfully added"
    else
      flash[:danger] = @directory.errors.full_messages.join(",")
    end
  end

  def show
    if params[:dir_id].present?
      @directory = Directory.find(params[:dir_id]).directoriable
    elsif params[:id].present?
      @directory = Directory.find(params[:id])
    end
  end

  def destroy
    @directory = Directory.find(params[:id])
    @object = @directory.directoriable

    if params[:directory_id]
      @dir = @directory.document_documentables
      @dir.each do |doc|
        @document = Document.find(doc.document_id)
        @document.destroy
        doc.destroy
      end
      if @directory.destroy
        flash[:success] = "Permanant delete"
      else
        flash[:danger] = "Not delete"
      end

      @directory = Directory.find(params[:directory_id])
    else
      @dir =  @directory.document_documentables
      @dir.each do |doc|
        @document = doc.document
        @document.destroy
      end
      if @directory.destroy
        flash[:success] = "Directory Successfully deleted"
      else
        flash[:danger] = @directory.errors.full_messages.join(",")
      end
      @directory = Directory.where(directoriable: current_contact.lead_client_contact.contactable).where(name: nil).first
    end

    #@directory = @company.directory
    @directories = @directory.directories
    @documents = @directory.documents
  end

  def edit
    @directory = Directory.find(params[:id])
  end

  def update
    @directory = Directory.find(params[:id])
    @directory.update_attributes(directory_params)
  end

  def index
    if params[:directory_id].present?
      @directory =Directory.find(params[:directory_id])
    else
      @directory = Directory.where(directoriable: current_contact.lead_client_contact.contactable).where(name: nil).first
    end
    @directories = @directory.directories
    @documents = @directory.documents
  end

  def system_files
    @directory = Directory.where(directoriable: current_contact.lead_client_contact.contactable).where(name: 'system_dir').first
    @documents = @directory.documents
  end

  def destroy_all
    @all_directories = Directory.where(id: params[:ids])
    @directory =  @all_directories.first.directoriable
    @directories = @directory.directories
    @documents = @directory.documents
    @all_directories.destroy_all
  end

  private

  def directory_params
      params.require(:directory).permit(:name, :directoriable_type, :directoriable_id)
  end
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController

  def new
    @directory = Directory.new(directoriable_type: params[:directoriable_type], directoriable_id: params[:directoriable_id])
  end


  def create
    @directory = Directory.new(directory_params.merge({ resourcable: current_user || current_contact}))
    if @directory.save
      flash[:success] = "Directory successfully added"
    else
      flash[:danger] = @directory.errors.full_messages.join(",")
    end
  end

  def show
    if params[:dir_id].present?
      @directory = Directory.find(params[:dir_id]).directoriable
    elsif params[:id].present?
      @directory = Directory.find(params[:id])
    end
  end

  def destroy
    @directory = Directory.find(params[:id])
    @object = @directory.directoriable

    if params[:directory_id]
      @dir = @directory.document_documentables
      @dir.each do |doc|
        @document = Document.find(doc.document_id)
        @document.destroy
        doc.destroy
      end
      if @directory.destroy
        flash[:success] = "Permanant delete"
      else
        flash[:danger] = "Not delete"
      end

      @directory = Directory.find(params[:directory_id])
    else
      @dir =  @directory.document_documentables
      @dir.each do |doc|
        @document = doc.document
        @document.destroy
      end
      if @directory.destroy
        flash[:success] = "Directory Successfully deleted"
      else
        flash[:danger] = @directory.errors.full_messages.join(",")
      end
      @directory = @company.directories.where(name: nil).first
    end

    #@directory = @company.directory
    @directories = @directory.directories
    @documents = @directory.documents
  end

  def edit
    @directory = Directory.find(params[:id])
  end

  def update
    @directory = Directory.find(params[:id])
    @directory.update_attributes(directory_params)
  end

  def index
    if params[:directory_id].present?
      @directory =Directory.find(params[:directory_id])
    else
      @directory = @company.directories.where(name: nil).first
    end
    @directories = @directory.directories
    @documents = @directory.documents
  end

  def system_files
    @directory = @company.directories.where(name: 'system').first
    @documents = @directory.documents
  end

  def destroy_all
    @all_directories = Directory.where(id: params[:ids])
    @directory =  @all_directories.first.directoriable
    @directories = @directory.directories
    @documents = @directory.documents
    @all_directories.destroy_all
  end

  private

  def directory_params
      params.require(:directory).permit(:name, :directoriable_type, :directoriable_id)
  end
end

app/helpers/contacts/directories_helper.rb
module Contacts::DirectoriesHelper
end

app/helpers/directories_helper.rb
module DirectoriesHelper

  def last_update(directory)
    document = directory.documents.present? ?  directory.documents.first : nil
    directories = directory.directories.present? ?  directory.directories.first : nil

    if document.present? || directories.present?
      document.present? ? (directories.present? ?  ((document.created_at < directories.created_at) ? directories.created_at.strftime("%m/%d/%Y, %I:%M %p") : document.created_at.strftime("%m/%d/%Y, %I:%M %p") )  : document.created_at.strftime("%m/%d/%Y, %I:%M %p") ) : directories.created_at.strftime("%m/%d/%Y, %I:%M %p")
    else
      directory.created_at.strftime("%m/%d/%Y, %I:%M %p")
    end

  end
end

app/views/directories/_directory.html.erb
<div class="dynmic-tab-div directory-structure">
  <div class="row">
    <div class="col-sm-12">
      <div class="dynmic-tab-div-header">

        <% if object.class.name == 'Directory' %>
          <% path = object.directoriable.class.name == 'Directory' ? directory_path(object.directoriable) : directory_path(dir_id: object.id, id: object.id)  %>
          <%= link_to path, remote: true, class: "m-l-10" do%>
            <i class="fa fa-arrow-left"></i>
          <% end %>
        <%end%>
        <span class="heading"><%= object.class.name == 'Directory' ? object.name : "" %></span>
          <div class="pull-right">

          <%#= link_to new_directory_path(directoriable_type: object.class, directoriable_id: object.id), remote: true, class: " pull-right m-r-10", title: 'Add Directory' do %>
            <!-- <i class="fa fa-plus" aria-hidden="true"></i> -->
            <!-- <i class="fa fa-folder" aria-hidden="true"></i> -->
          <%# end %>
          <%= link_to new_document_path(documentable_type: object.class, documentable_id: object.id), remote: true, class: "m-r-10  pull-right", title: 'Add File' do %>
            <i class="fa fa-plus" aria-hidden="true"></i>

            <i class="fa fa-file" aria-hidden="true"></i>
          <%end%>

        </div>
      </div>
      <div class="dynmic-tab-div-data ">
        <div class="row">
          <div class="col-md-12 ">
          </div>
          <%= render partial: 'documents/list_document', locals: {object: object}%>
          <%
=begin%>
 <%object.documents.each do |document|%>
            <%= render partial: 'documents/list_document', locals: {document: document}%>
          <%end%>
<%
=end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/directories/_directory_content.html.erb
<div class="admin-table bg-white table-responsive p-4">
  <table class="common-data-table table table-bordered text-center lead_table" id="dirs">
    <thead>
      <tr>
        <th>
          <div class="radio-lbl">
            <label class="check ">
              <input type="checkbox"  name="" id="check-all">
              <span class="checkmark"></span>
            </label>
          </div>
        </th>
        <th class="text-left">
          Name
        </th>
        <th> Created By </th>
        <th>
          Last Updated At
        </th>
      </tr>
    </thead>

    <tbody>
      <%if directory.directoriable_type == 'Directory'%>
        <tr>
          <td></td>
          <td class="text-left">
            <%= link_to directories_path(directory_id: directory.directoriable_id), class:"common-link" do%>
              <i class="fa fa-folder-o"> </i> ...
            <% end %>
          </td>
          <td></td>
          <td></td>
        </tr>
      <%end%>
      <% directory.directories.each do |directory|%>
        <tr>
          <td>
            <div class="radio-lbl">
              <label class="check ">
                <%= check_box_tag "directory_id[]", directory.id , false, class:"check directory-checkbox", data: {id: directory.id} %>
                <span class="checkmark"></span>
              </label>
            </div>
          </td>
          <!-- <td> <%#= link_to directory_path(directory, directory_id: (params[:directory_id].present? ?  params[:directory_id] : directory.get_directory) ), method: :delete,remote: true, class:"common-link" do %> <i class="fa fa-trash" aria-hidden="true"></i><%# end %> </td> -->

          <td class="text-left">
            <%= link_to directories_path(directory_id: directory.id), class:"common-link" do%>
              <i class="fa fa-folder-o" area-hidden='true'> </i> <%= directory.name %>
            <% end %>
          </td>
          <td> <%= directory.resourcable.fullname %> </td>
          <td><%= last_update(directory) %>   <%#= directory.created_at.strftime("%m/%d/%Y, %I:%M %p") %></td>
        </tr>
      <%end%>

      <% directory.documents.each do |document| %>
        <tr>
          <td>
            <div class="radio-lbl">
              <label class="check ">
                <%= check_box_tag "document_ids[]", document.id , false, class:"check document-checkbox", data: {id: document.id} %>
                <span class="checkmark"></span>
              </label>
            </div>
          </td>
          <!-- <td>
            <%#= link_to document_path(document,directory_id: (params[:directory_id].present? ?  params[:directory_id] : document.get_directory) ), method: :delete, remote: true, class:"common-link" do %> <i class="fa fa-trash" aria-hidden="true"></i> <%# end %>
          </td> -->
          <td class="text-left">
            <%= link_to document.attachment.url, target: '_blank', class:"common-link" do%>
              <% extension = document.attachment.try(:file).try(:extension).try(:downcase) %>
              <% if extension == "jpg" || extension == "png" || extension == "jpeg"  %>
              <%= image_tag document.attachment.url, :size => "35x35" %>
              <% elsif extension == "pdf" %>
              <img src="/assets/icon_PDF_big.png" class="file-icon" width="35" height="35">
              <% else %>
              <img src="/assets/icon_Generic_big.png" class="file-icon" width="35" height="35">
              <% end %>
             <%= document.attachment.file.filename.truncate(30) %>
            <% end %>
          </td>
          <td> <%= document.try(:resourcable).try(:fullname) %> </td>
          <td>
            <%= document.created_at.strftime("%m/%d/%Y, %I:%M %p") %>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<script type="text/javascript">

  $(document).ready(function(){
    if ( $.fn.DataTable.isDataTable('#dirs') ) {
        $('#dirs').DataTable().destroy();
    }
    $('#dirs').DataTable({
      sDom: 'lfrtip',
      scrollX: false,
      autoWidth: false,
      paging: true,
      pageLength: 25,
      // bLengthChange: false,
      searching: true,
      lengthMenu: [25,50, 100],
      // colReorder: {
      //   fixedColumnsLeft: 1
      // },
      columnDefs: [
        {orderable: false, targets: [0]},
        {width: "30px", targets: [0] },
        {className: "dt-center", targets: "_all"}
      ],
      order: [],
    });
  });
</script>

app/views/directories/_document.html.erb
<div class="block-ui-box m-t-5">
  <div class="col-md-12">
    <%= link_to "Add Directory", new_directory_path(directoriable_type: lead.class, directoriable_id: lead.id),  remote: true %>
    <%= link_to "Add Document", new_document_path(documentable: lead),  remote: true %>
  </div>
  <%lead.directories.each do |dir|%>
    <%= render partial: 'directories/list_directory', locals: {dir: dir}%>
  <%end%>
  <%lead.documents.each do |document|%>
    <%= render partial: 'documents/list_document', locals: {document: document}%>
  <%end%>
</div>
<div id='directories'></div>

app/views/directories/_form.html.erb
<div class="col-md-12">
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>
</div>

app/views/directories/_list.html.erb
<div id='directory_content'>
  <%= render partial: 'directories/directory_content', locals: {directory: directory}%>
</div>
<%if directory.name != 'system' %>
  <% if checked_permission?(current_user, @klass_list["Document"], @action_list["create"]) %>
    <div class="row m-t-20">
      <div class="col-sm-12 mobile-center">
        <%= form_for Document.new, url: uploadfiles_path, html: {multipart: true, class: 'dropzone', id: 'dir-dropzone', method: :post} do |f| %>
          <div id='flash_message'></div>

          <div id='content'>
            <div class="dz-message needsclick">
              <h3> Add new file here </h3> or
              <strong> Click </strong> to upload
            </div>
            <div class="fallback">
              <%= f.file_field :attachment %>
              <%= f.submit 'Upload Document'%>
            </div>

          </div>
        <%end%>
      </div>
    </div>
  <%end%>
<%end%>


<script type="text/javascript">

  $(document).ready(function(){
    $('#destroy_all').on('click', function(){

      //if document destroy then remove selected document
      $('.remove-document').trigger('click');
      
      var checkedDir = [];
      var checkedDoc = [];
      $("input[name='directory_id[]']:checked").each(function (){
        checkedDir.push(parseInt($(this).val()));
      });
      $("input[name='document_ids[]']:checked").each(function (){
        checkedDoc.push(parseInt($(this).val()));
      });
      if(checkedDir == 0 && checkedDoc == 0){
        confirm("Please select Directory Or Document.");
      }else{
        if(checkedDir != 0){
          $.ajax({
            url: "<%= destroy_all_directories_path %>",
            beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
            type: 'DELETE',
            data: {
              ids: checkedDir
            },
            dataType: "script",
            success: function(result){
            }
          });
        }
        if(checkedDoc != 0){
          $.ajax({
            url: "<%= destroy_all_documents_path %>",
            beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
            type: 'DELETE',
            data: {
              ids: checkedDoc
            },
            dataType: "script",
            success: function(result){
            }
          });
        }
      }
    });
    $('.document-checkbox').change(function(){
      if($(this).prop('checked')){
        // $(".directory-checkbox").attr("disabled", true);
      }else{
        if($('.document-checkbox').filter(':checked').length == 0){
          $(".directory-checkbox").attr("disabled", false);
        }
      }
    });
    $('.directory-checkbox').change(function(){
      if($(this).prop('checked')){
        // $(".document-checkbox").attr("disabled", true);
      }else{
        if($('.directory-checkbox').filter(':checked').length == 0){
          $(".document-checkbox").attr("disabled", false);
        }
      }
    });

    $('#check-all').on('change', function(){
      $('#directory_content .check').prop('checked', $(this).prop('checked'));
      checked_checkbox_count()
    });
    resourcable_type = "<%= current_user.class.name %>";
    resourcable_id = "<%= current_user.id %>";
    documentable_type = "<%= @directory.class.name %>";
    documentable_id = "<%= @directory.id %>";
    $(function(){
      Dropzone.autoDiscover = false;
      myDropzone = $('#dir-dropzone').dropzone({
        maxFileSize: 10,
        addRemoveLinks: true,
        paramName: 'document[attachment]',
        init: function() {
          this.on("sending", function(file, xhr, formData) {
            formData.append("document[resourcable_type]", resourcable_type);
            formData.append("document[resourcable_id]", resourcable_id);
            formData.append("documentable_type", documentable_type);
            formData.append("documentable_id", documentable_id);
            console.log(formData)
          });
          this.on("success", function(file,res){
            this.removeFile(file);
          });
          this.on("complete", function (file) {
            $.ajax({
              url: "<%= update_documents_documents_url %>",
              data: {
                directory_id: documentable_id
              }
            })
          });
        }
      });
    });
  });

</script>

app/views/directories/_list_directories.html.erb
<div class="row row m-t-10 m-b-10">
  <h3 class="m-l-15 m-b-5"> Folders </h3>

  <%if directory.directoriable_type == 'Directory'%>
    <div class="col-md-3">
      <%= link_to directory_path(directory.directoriable), remote: true,class:"common-link" do%>
        <i class="fa fa-folder"> </i> ...
      <% end %>
    </div>
  <%end%>
  <% directory.directories.each do |dir| %>
    <div class="col-md-3">
      <%= link_to directory_path(dir), remote: true,class:"common-link"  do%>
        <i class="fa fa-folder"> </i> <%= dir.name %>
      <% end %>
    </div>
  <% end %>
  <div class="col-md-3" id='new-directory'>
    <%= link_to new_directory_path(directoriable_type: directory.class.name, directoriable_id: directory.id), remote: true,class:"common-link" do %>
      <i class="fa fa-folder"> </i> + Add Folder
    <% end %>
  </div>
  <div id='new_dir_field' class="hidden">

  </div>
</div>
<script>
  $(document).ready(function(){

  });
</script>

app/views/directories/_list_directory.html.erb
<div class="col-md-12">
  <div class="col-md-4">
    <%= link_to directory_path(directory), remote: true do%>
      <i class="fa fa-folder" aria-hidden="true"></i>
      <%=  directory.name%>
    <% end %>
  </div>
  <div class="col-md-3">

    <%= link_to edit_directory_path(directory), remote: true do%>
    <i class="fa fa-pencil" aria-hidden="true"></i>
    <%end%>
    <%= link_to directory_path(directory),data: { confirm: "Are you sure you want to Delete this Directory?" }, method: :delete, remote: true do%>
      <i class="fa fa-trash" aria-hidden="true"></i>
    <%end%>
  </div>
</div>