config/routes.rb
  resources :leads do
    resources :comments, only: [:create, :update,:index]
    #resources :tasks
    collection do
      delete 'destroy_all'
      get 'import_leads'
      post 'import_map'
      get 'assign_all', to: 'leads#new_assign_all'
      post 'assign_all'
    end
    member do
      get 'convert_client'
      get 'edit_summary'
    end
  end
  post 'import_file' => 'leads#import_file'
  get 'import_form' => 'leads#import_form'
  resources :contacts do
    collection do
      get 'check_email'
      get 'resend_invitation'
      get 'lead_contacts'
      get 'client_contacts'
      get 'vendor_contacts'
      delete 'destroy_all'
    end
  end

  resources :project_tasks
  get 'search_auto_complete_data_tasks' => 'project_tasks#search_auto_complete_data_tasks', :as => "search_auto_complete_data_tasks"
  resources :projects do
    collection do
      delete 'destroy_all'
      get 'user_list'
      get 'list'
      post 'send_project_invitaiton'
      get 'project_user_list'
    end
    member do
      get 'overview'
      get 'invite_for_project'
      get 'project_details'
      get 'accept_user_invitation'
    end
    resources :messages do
      delete 'comment_delete'
    end
    resources :project_documents
  end

  get 'project_communication_dashborad' => 'projects#project_communication_dashborad', as: :project_communication_dashborad
  get "back_to_project/:id" => "projects#back_to_project", as: :back_to_project

  resources :messages
  resources :tickets do
    collection do
      delete 'destroy_all'
      get 'contacts_list'
      get 'user_list'
      get 'list'
      post 'send_ticket_invitaiton'
      get 'ticket_user_list'
      get 'reports'
      post 'download_attachment', to: 'tickets#download_attachment', as: :download_attachment
    end
    member do
      get 'overview'
      get 'invite_for_ticket'
      get 'ticket_details'
    end
    resources :messages do
      delete 'comment_delete'
      get 'reply_edit'
      patch 'reply_update'
      delete 'reply_delete'
    end
    resources :ticket_documents
  end

  get 'autocomplete_data' => 'tickets#autocomplete_data', :as => "autocomplete_data_tickets"
  get 'back_to_ticket/:id' => 'tickets#back_to_ticket', as: :back_to_ticket


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#dashboard'
  resources :settings do
    collection do
      get 'module', as: :module
      get 'actions'
      get 'users_settings', as: :users
      get 'module_select'
      get 'email'
      get 'revoke_mail_access'
      resources :users do
        delete 'remove_image'
        get 'signature'
        patch 'update_signature'
        patch 'upload_image'

        get 'resend_invitation'
      end
      get 'new_image' => 'users#new_image'
      resources :roles
    end
  end
  resources :groups do
    collection do
      get :change_position
    end
  end
  resources :fields do
    collection do
      get :change_position
      patch :change_position_in_table
      patch :change_header_view
      patch :toggle_visible_in_table
    end
    member do
      patch :change_properties
    end
  end
  resources :field_picklist_values do
    collection do
      get :change_klass
      get :change_field
      get :change_position
    end
  end
  resources :custom_values
  get '/dashboard', to: 'home#dashboard'

  resources :clients do
    resources :comments, only: [:create,:update,:index]
    resources :inventory_associations, module: :clients, only: [:index] do
      collection do
        get :subcategories
        get :inventory_groups
        get :inventory_group
        get :inventory_groups_by_sku
        get :bulk_new
        post :bulk_create
      end
    end
    resources :shipments, module: :clients, only: [:new, :create] do
      get 'package_label/:id', to: 'shipments#package_label', as: :package_label
    end
    resources :employees, module: :clients do
      member do
        get 'feedback'
      end
    end
    collection do
      delete :destroy_all
      get 'import_clients'
      post 'import_map'
      get 'select_client'
      get 'status_board'
      post 'update_status_board'
      get 'department_details'
      get :client_by_merchant_id
    end
    post 'set'
    member do
      get 'edit_summary'
      get 'send_menu_approval_email'
      get 'send_menu_approval_sms'
      get 'logs'
    end
  end
  post 'import_file_client' => 'clients#import_file_client'
  get 'import_form_client' => 'clients#import_form_client'

  resources :vendors do
    member do
      get 'edit_summary'
    end
    collection do
      delete :destroy_all
    end
  end


  get 'page1', to: 'home#page1'
  get 'project_communication_dashborad1', to: 'home#project_communication_dashborad1'
  resources :module_numbers
  get 'page2', to: 'home#page2'
  get "get_module_name" => "module_numbers#get_module_name"
  get 'privacy', to: 'home#privacy'
  get 'view_map', to: 'home#view_map'

  resources :invoices do
    collection do
      delete :destroy_all
      get :inventories
      get :clients
    end
    get 'email'
    post 'email_create'
    get 'preview'
    get 'download'
    resource :payment, except: [:edit, :update, :destroy]
  end

  resources :directories do
    collection do
      delete 'destroy_all'
      get 'system_files'
    end
  end
  resources :documents do
    collection do
      delete :destroy_all
      get 'upload_document'
      get 'update_documents'
      get 'selected_documents'
    end
  end

  resources :tasks do
    collection do
      delete :destroy_all
    end
    post :mark_as_completed
  end
  get 'back_to_task/:id', to: 'tasks#back_to_task', as: :back_to_task

  resources :notes do
    collection do
      delete :destroy_all
    end
  end
  get 'back_to_note/:id', to: "notes#back_to_note", as: :back_to_note
  resources :roles
  resources :emails do
    post :reply
    collection do
      get :sent
      get :draft
      get :connect
      get :update_draft
      get :create_draft
      delete 'destroy_draft/:id', to: 'emails#destroy_draft', as: 'destroy_draft'
    end
  end

  namespace :purchase_order do
    resources :devices, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :products, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :versions, only: [:show, :create]
  end

  resources :inventory_groups do
    collection do
      patch :setup_inventory_versions
      delete :destroy_all
      get :subcategories_for_category
    end
  end

  # Category Management
  resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :subcategories, only: [:new, :edit, :create, :update, :destroy]

  resources :inventories do
    collection do
      delete :destroy_all
      get :import
      post :import_map
      put :update_inventory_column
      get :subcategories_for_data_list
      post :import_file
    end
    member do
      get :logs
    end
  end

  resources :stock_adjustments, except: %i[index show]
  resources :email_templetes do
    collection do
      delete 'destroy_all'
    end
  end
  resources :template_dirs
  resources :cemails do
    collection do
      delete 'destroy_all'
    end
  end
  get "get_template" => "cemails#get_template", as: :get_template
  get "back_to_email/:id" => "cemails#back_to_email", as: :back_to_email

  resources :invoice_taxes
  resources :feedback_questions
  resources :feedbacks, only: [:create] do
    collection do
      get :employee
      post :send_otp
      post :verify_otp
    end
  end

  resources :meetings do
    collection do
      delete :destroy_all
      get :calendar
      get :calendar_meetings
      post :calendar_day_meetings
    end
  end

  namespace :project_management do
    resources :projects do
      collection do
        get :list
        get :contacts_form
      end
      resources :tasks, except: [:index] do
        resources :comments, only: [:index, :create, :destroy]
      end
    end
  end

  namespace :public do
    resources :help_desks, only: [:index, :show]
    resources :clients, only: [:edit, :update] do
      member do
        get :status
      end
    end
  end

  resources :help_desks

  namespace :contract do
    resources :templates
    resources :contracts
  end

  resources :kpis, only: [:index] do
    collection do
      get :sales
      post :sales_lead_contracts_pipeline
      post :sales_lead_status
      post :won_clients
      get :marketing
      post :marketing_lead_statistics
      get 'account_manager_performance'
    end
  end

  namespace :file_manager do
    resources :file_associations, only: [:edit, :update, :destroy] do
      collection do
        get :bulk_new
        post :bulk_create
      end
    end
    resources :files, only: [] do
      collection do
        post :bulk_create
        get :selected_files
      end
    end
  end

  resources :reports, only: [:index] do
    collection do
      get 'deployment'
      get 'ipos_login_details'
    end
  end

  resources :ipos_marketing_tools

  # User::TimeSheet routes
  resources :users, module: :users, only: [] do
    resources :time_sheet_logs, except: [:show] do
      collection do
        get 'clock_in_out_toggle'
      end
    end
    collection do
      get 'time_sheet_logs/all_users'
      get 'time_sheet_logs/settings'
      post 'time_sheet_logs/update_settings'
    end
  end

  namespace :third_party do
    get 'sso', to: 'sso#create'
  end

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :tasks, only: [:index] do
        collection do
          put 'update_task'
          post 'clear_data'
        end
      end
      resources :user_task_logs, only: [] do
        collection do
          put 'checkin'
          put 'checkout'
        end
      end
      resources :employees, only: [:index, :create, :destroy] do
        collection do
          post 'employee_create'
        end
      end

app/models/note.rb
# TODO: FIXME: user_id is not treated as a foreign key
class Note < ApplicationRecord
  audited

  scope :ordered, -> { order(created_at: :desc) }

  belongs_to :user
  belongs_to :noteable, polymorphic: true

  has_many :document_documentables, as: :documentable, dependent: :destroy
  has_many :documents, through: :document_documentables

  def field_data
    field_name = Field.where(klass_id: Klass.find_by(name: "Note"))
    field_name.each do |name|
      if name.name == "content"
        return true
      end
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_klass

  def new
    @note = Note.new(noteable_type: params[:noteable_type], noteable_id: params[:noteable_id])
    @klass = Klass.find_by(name: "Note")
    @groups = Group.includes(:fields).where(klass: @klass)
  end

  def create
    @note = Note.new(note_pramas)
    @note_klass = Klass.find_by(name: "Note")
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
    if @note.noteable_type == "Lead"
      @object = Lead.find(@note.noteable_id)
    elsif @note.noteable_type == "Client"
      @object = Client.find(@note.noteable_id)
    end
    if @note.save
      create_document(@note, params[:document_ids], params[:attachments],current_user)
      flash[:success] = 'Note Successfully Added!'
    else
      flash[:danger] = @note.errors.full_message.join(",")
    end
    @note_show = Note.new
  end

  def index
    @from_page = 'index'
    if params[:noteable_type] == "Lead"
      @object = Lead.find(params[:noteable_id])
    elsif params[:noteable_type] == "Client"
      @object = Client.find(params[:noteable_id])
    end
    @note_klass = Klass.find_by(name: "Note")
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
  end

  def show
    @note = Note.find(params[:id])
    @klass = Klass.find_by(name: "Note")
    @fields = current_user.fields_for_table_with_order(klass: @klass)
    @object = @note.noteable
  end

  def edit
    @note = Note.find(params[:id])
    @note_klass = Klass.find_by(name: "Note")
    @groups = Group.includes(:fields).where(klass: @note_klass)
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
    if @note.noteable_type == "Lead"
      @object = Lead.find(@note.noteable_id)
    elsif @note.noteable_type == "Client"
      @object = Client.find(@note.noteable_id)
    end
  end

  def update
    @note = Note.find(params[:id])
    @note_klass = Klass.find_by(name: "Note")
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
    if @note.noteable_type == "Lead"
      @object = Lead.find(@note.noteable_id)
    elsif @note.noteable_type == "Client"
      @object = Client.find(@note.noteable_id)
    end
    if @note.update(note_pramas)
      create_document(@note, params[:document_ids], params[:attachments],current_user)
      flash[:success] = 'Note Successfully Updated!'
    else
      flash[:danger] = @note.errors.full_message.join(",")
    end
    @note_show = Note.new
  end

  def destroy
    @note = Note.find(params[:id])
    @note_klass = Klass.find_by(name: "Note")
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
    if @note.noteable_type == "Lead"
      @object = Lead.find(@note.noteable_id)
    elsif @note.noteable_type == "Client"
      @object = Client.find(@note.noteable_id)
    end
    if @note.destroy
      flash[:success] = 'Note Successfully Deleted!'
    else
      flash[:danger] = @note.errors.full_message.join(",")
    end
    @note_show = Note.new
  end

  def destroy_all
    @notes = Note.where(id: params[:ids])
    if params[:noteable_type] == "Lead"
      @object = Lead.find(params[:noteable_id])
    elsif params[:noteable_type] == "Client"
      @object = Client.find(params[:noteable_id])
    end
    if @notes.destroy_all
      flash[:success] = 'Selected Notes Successfully Deleted!'
    else
      flash[:danger] = 'Something Went Wrong While Deleting Selected Notes!'
    end
    @notes = Note.all
    @note_klass = Klass.find_by(name: "Note")
    @note_show = Note.new
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
  end

  def back_to_note
    @note = Note.find(params[:id])
    if @note.noteable_type == "Lead"
      @object = Lead.find(@note.noteable_id)
    elsif @note.noteable_type == "Client"
      @object = Client.find(@note.noteable_id)
    end
    @note_klass = Klass.find_by(name: "Note")
    @note_fields = current_user.fields_for_table_with_order(klass: @note_klass)
  end

  private
  def note_pramas
    params.require(:note).permit(:content, :attachment, :noteable_type, :noteable_id, multi_select_params_permit(@klass)).merge(user_id: current_user.id)
  end

  def set_klass
    @klass = Klass.find_by(name: 'Note')
    @data = {}
    fields = Field.where(klass: @klass, have_custom_value: true)
    fields.each do |field|
      @data[field.name.to_sym] = field.field_picklist_values.pluck(:value)
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_index.html.erb
<%action_delete =  checked_permission?(current_user, @klass_list['Note'], @action_list['delete']) %>
<%action_update =  checked_permission?(current_user, @klass_list['Note'], @action_list['update']) %>
<%action_create =  checked_permission?(current_user, @klass_list['Note'], @action_list['create']) %>
<%action_read =  checked_permission?(current_user, @klass_list['Note'], @action_list['read']) %>
<div class="dynmic-tab-div directory-structure">
  <div class="row">
    <div class="col-sm-12">
      <div class="dynmic-tab-div-header">
        <span class="heading"><%#= "Note" %></span>
        <div class="pull-right">
          <% if checked_permission?(current_user, @klass_list['Note'], @action_list['delete'])%>
            <a href="javascript:void(0)" class="site-content-head-btn" id='destroy_all_notes'>
              Delete
            </a>
          <%end%>
          <% if checked_permission?(current_user, @klass_list['Note'], @action_list['create'])%>
            <%= link_to  new_note_path(noteable_type: object.class,noteable_id: object.id), remote: true, class: "site-content-head-btn" do %>
              + Add Note
            <%end%>
          <%end%>
          <div class="dropdown action-dropdown">
            <button class="action-dropdown-btn dropdown-toggle" type="button" data-toggle="dropdown">Action
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li>
               <%= link_to "Edit Column", actions_settings_path(klass_id: Klass.find_by(name: 'Note').id, url: notes_path(noteable_id: object.id, noteable_type: 'Lead')), class: 'dropdown-item', remote: true%>
              </li>
              <li>
                <%= link_to "Edit Properties", module_settings_path(klass_id: Klass.find_by(name: 'Note').id), class: 'dropdown-item'%>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="dynmic-tab-div-data ">
        <div class="row">
          <div class="col-sm-12">
            <div class="site-content-data">
              <div id="note-list" class="table-list">
                <%= render partial: 'notes/note_list', locals: { object: object, note_fields: note_fields, list: list } %> <%# object.notes %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $(".dropdown-toggle").dropdown();
  });
</script>

app/views/notes/_note_list.html.erb
<%action_delete =  checked_permission?(current_user, @klass_list['Note'], @action_list['delete']) %>
<%action_update =  checked_permission?(current_user, @klass_list['Note'], @action_list['update']) %>
<%action_create =  checked_permission?(current_user, @klass_list['Note'], @action_list['create']) %>
<%action_read =  checked_permission?(current_user, @klass_list['Note'], @action_list['read']) %>
<div class="table-responsive">
  <table class="common-data-table text-center" id="notes">
    <thead>
      <th>
        <div class="radio-lbl">
          <label class="check ">
            <input type="checkbox"  name="" id="check-all">
            <span class="checkmark"></span>
          </label>
        </div>
      </th>

      <th> Action</th>
      <% note_fields.each do |field|%>
        <th data-id="<%=field.id%>"><%=field.label %></th>
      <%end%>
    </thead>

    <tbody class="list-body">
      <% object.notes.ordered.each do |note| %>
        <%#= form_for note, local: true, class: 'form-inline' do |f| %>
        <tr>
          <td>
            <div class="radio-lbl">
              <label class="check ">
                <%= check_box_tag "note_ids[]", note.id , false, class:"check" %>
                <span class="checkmark"></span>
              </label>
            </div>
          </td>
          <td>
            <div class="btn-wrapper">
              <%if action_read%>
                <div class="action-icon">
                 <%= link_to note_path(note,list: list) do %>
                   <i class="fa fa-eye" aria-hidden="true"></i>
                 <% end %>
                </div>
              <%end%>
              <%if action_update%>
                <div class="action-icon">
                  <%= link_to edit_note_path(note),remote: true do %>
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                  <% end %>
                </div>
              <%end%>
              <%if action_delete%>
                <div class="action-icon">
                  <%= link_to note_path(note),data: { confirm: "Are you sure you want to Delete this Note?" },method: :delete,remote: true do %>
                    <i class="fa fa-trash " aria-hidden="true"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          </td>

          <% note_fields.each do |field| %>
            <td data-id="<%= note.id %>" data-klass='Note' data-field="<%= field.name%>" data-deletable="<%= field.deletable%>" class="<%= action_update ?  'note-editable' : '' %>" >
              <div class="info-dynamic-data note-value fs-13">
                <% if field.column_type == 'Multi-Select Check Box' %>
                  <%= parse_multi_select(note.send(field.name)) %>
                <% else %>
                  <% case field.name %>
                  <% when "content" %>
                    <% if note.documents.present? %>
                      <strong><i class="fa fa-paperclip m-r-5" aria-hidden="true"></i></strong>
                    <% end %>
                    <div class='d-inline-block'><%= note.send(field.name).truncate_html(300).html_safe %></div>
                  <% when "attachment" %>
                    <% if note.documents.present? %>
                      <% note.documents.each do |attach| %>
                        <%= link_to attach.attachment.url, target: 'blank', title: attach.attachment.file.filename do %>
                          <i class="fa fa-file" aria-hidden="true"></i>
                          <%= attach.attachment.file.filename.truncate(20) %>
                        <%end%>
                        <br/>
                      <% end %>
                    <% else %>
                      No Attachment Added
                    <% end %>
                  <% when "created_at" %>
                    <%= note.send(field.name)&.strftime("%m/%d/%Y, %I:%M %p") %>
                  <% when "user_id" %>
                    <%= note.user.fullname %>

                  <% else %>
                    <%= note.send(field.name) %>
                  <% end %>
                <% end %>
              </div>

              <%if field.name != 'created_at'%>
                <div class="form-group field hidden">
                  <%#= render partial: 'forms/field', locals: { f: f, field_name: field.name, field_label: nil, column_type: field.column_type, custom: field.custom, have_custom_value: field.have_custom_value, field: field, value: note.send(field.name), disp_lable: false } %>
                </div>
              <%end%>

            </td>
          <% end  %>
        </tr>
        <%# end %>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function(){
    if ( $.fn.DataTable.isDataTable('#notes') ) {
      $('#notes').DataTable().destroy();
    }
    $('#notes').DataTable({
      sDom: 'lfrtip',
      scrollX: false,
      autoWidth: false,
      paging: false,
      searching: true,
      lengthMenu: [50, 100],
      // colReorder: {
      //   fixedColumnsLeft: 1
      // },
      columnDefs: [
        {orderable: false, targets: [0,1]},
        {width: "30px", targets: [0] },
        {className: "dt-center", targets: "_all"}
      ],
      order: []
    });

    $('#check-all').on('change', function(){
      $('.list-body .check').prop('checked',$(this).prop('checked'));
    });
    $('#destroy_all_notes').on('click', function(){
      var checked = []
      $("input[name='note_ids[]']:checked").each(function ()
      {
          checked.push(parseInt($(this).val()));
      });
      if(checked == 0){
        confirm("Please select any note");
      }else{
        $.ajax({
          url: "<%= object ? destroy_all_notes_path(noteable_type: object.class,noteable_id: object.id) : destroy_all_notes_path %>",
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          type: 'DELETE',
          data: {
            ids: checked
          },
          dataType: "script",
          success: function(result){
          }
        });
      }
    });

    // $('.note-editable .note-value').on('click', function(){
    //   debugger;
    //   if('<%= @from_page%>' != 'index'){
    //     var text = $.trim($(this).text());
    //     var dataId = $(this).parent().data('id');
    //     var field = $(this).parent().data('field');

    //     // var editable = $(this).parent().data('editable');
    //     // if(editable==true){
    //     //$(this).parent().html("<input class='note-update-"+dataId+" form-control' value='"+text+"' data-id = '"+ dataId +"' data-klass='"+$(this).parent().data('klass')+"'  style= 'width:"+$(this).parent().width()+"px;'  />");
    //       $('.note-editable').on('blur', function(e){
    //         debugger;
    //         //var key = e.which;
    //         //if(key == 13 || key ==9)  // the enter key code
    //         //{
    //           data = {}
    //           data[field] = $(this).val();
    //           $.ajax({
    //             url: "/notes/" + dataId,
    //             beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
    //             type: 'patch',
    //             data: {
    //               note: data
    //             },
    //             dataType: "script",
    //             success: function(result){
    //             }
    //           });
    //         //}
    //       });
    //     //}
    //   }
    // });

    $('.custom-editable span').on('click', function(){
      var text = $.trim($(this).text());
      var dataId = $(this).parent().data('id');
      $(this).parent().html("<input class='custom-update-"+dataId+" form-control' value='"+text+"' data-id = '"+ dataId +"' data-klass='"+$(this).parent().data('klass')+"'   />");
      $('.custom-update-'+dataId).on('blur', function(){
        data = {value: $(this).val()};
        $.ajax({
          url: "/custom_values/" + dataId,
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          type: 'patch',
          data: {
            custom_value: data
          },
          dataType: "script",
          success: function(result){
            $.ajax({url: "/notes/",
              type: 'get',
              data: {
              },
              dataType: "script",
            });
          }
        });
      });
    });

    $('.custom-create span').on('click', function(){
      var text = $.trim($(this).text());
      var dataId = $(this).parent().data('id');
      var fieldId = $(this).parent().data('field-id');
      var dataKlassId = $(this).parent().data('klass-id');
      var dataKlass = $(this).parent().data('klass');
      $(this).parent().html("<input class='custom-update-"+dataId+" form-control' value='"+text+"' data-id = '"+ dataId +"' data-klass='"+$(this).parent().data('klass')+"'   />");
      $('.custom-update-'+dataId).on('blur', function(){
        data = {value: $(this).val(), field_id: fieldId, valuable_id: dataKlassId, valuable_type: dataKlass };
        $.ajax({
          url: "/custom_values/" + dataId,
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
          type: 'patch',
          data: {
            custom_value: data
          },
          dataType: "script",
          success: function(result){
            $.ajax({url: "/notes/",
              type: 'get',
              data: {
              },
              dataType: "script",
            });
          }
        });
      });
    });

  });

</script>

app/views/notes/_note_on_show.html.erb
<% if checked_permission?(current_user, @klass_list['Note'], @action_list['create'])%>
  <div class="dynmic-tab-div pad-top-0">
    <div class="row">
      <div class="col-sm-12">
        <div class="dynmic-tab-div-header">
          <span class="heading">Notes</span>
        </div>
        <%= form_for note, remote: true, html: { multipart: true } do |f| %>
          <div class="dynmic-tab-div-data">
            <%= render partial: "notes/form_note", locals: {f: f, id: id} %>
            <%= f.hidden_field :noteable_type, value: object.class %>
            <%= f.hidden_field :noteable_id, value: object.id %>
            <%= f.submit "Save Note",class: 'btn btn-success m-t-10' %>
            <!-- </div> -->
          </div>
        <% end %>
      </div>
    </div>
  </div>
<%end%>
<% if checked_permission?(current_user, @klass_list['Note'], @action_list['read'])%>
  <div class="row">
    <div class="col-sm-12">
      <div class="dynmic-tab-div-header">
        <span class="heading">Recent Notes</span>
          <%# path = object.class == Client ? notes_path(object) : notes_path(object) %>
          <%= link_to "View More", notes_path(noteable_type: object.class , noteable_id: object.id), class: "site-content-head-btn pull-right"  if object.notes.count > 5 %>
      </div>
      <div class="dynmic-tab-div-data ">
        <% object.notes.ordered.first(5).each do |note| %>
          <%= render partial: "notes/note", locals: {note: note, list: list} %>
        <%end%>
        <%#= link_to "View more", client_comments_path(@client) if @client.comments.count > 10 %>
      </div>
    </div>
  </div>
<%end%>

app/views/notes/show.html.erb
<div class="site-main">
  <%= render 'layouts/sidebar'%>

  <div class="site-content">
    <div class="site-content-head">
      <div class="row">
        <div class="col-sm-12">
          <div class="l-menu">
            <span class="main-menu-sitecontent">Notes</span>
            <span class="sub-menu-sitecontent m-x-10"><i class="fa fa-angle-right"></i></span>
            <span class="sub-menu-sitecontent"><%= @object.class %></span>
          </div>
          <div class='pull-right'>
          <% if params[:list] == "Object" %>
            <%= link_to @note.noteable, class: 'btn btn-success back-btn-users' do %> Back <% end %>
          <% elsif params[:list] == "Index" %>
            <%= link_to notes_path(noteable_type: @note.noteable_type , noteable_id: @note.noteable_id), class: 'btn btn-success back-btn-users' do %>Back<% end %>
          <% end %>
          </div>
          <div class="pull-right">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
       <div class="col-sm-12">
          <div class="site-content-data">
            <div id="note-list" class="table-list">
              <%= render partial: 'notes/note_details', locals: { object: @object, note: @note, klass: @klass } %> <%# object.notes %>
            </div>
          </div>
       </div>
    </div>
    <div id="modalContainer-index" class='modal-right'></div>
  </div>
</div>