config/routes.rb
Rails.application.routes.draw do

  # Devise Routes / Authentication routes
  devise_for :contacts, path: 'contact_users', controllers: { passwords: 'contacts/passwords', sessions: 'contacts/sessions' }
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords', sessions: 'users/sessions' }
  namespace :users do
    resource :two_factor_authentication, controller: 'two_factor_authentication', only: [:new, :show, :create] do
      collection do
        get :resend_direct_otp
      end
    end
  end
  namespace :users do
    resources :tfa_phone_numbers, only: [:index, :new, :create, :destroy]
  end


  # Engine Routes
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'

  # Application Routes
  get 'authorize' => 'auth#gettoken'
  get 'mail/index'

  get 'home/index'
  get 'google_autication' => 'google_imap#authentication'
  get 'oauth2callback' => 'google_imap#callback'
  get 'get_access_code' => 'google_imap#get_access_code'

  get 'home/dashboard'
  resources :work_flows do
    collection do
      post 'builder'
      post 'action_builder'
    end
  end
  resources :companies do
    get 'logo_image'
    delete 'remove_logo'
  end
  resources :search
  resources :user_permissions
  namespace :contacts do
    root 'home#dashboard'
    resources :projects do
      member do
        get 'overview'
        get 'accept_contact_invitation'
        get 'project_details'
      end
      collection do
      end
      resources :messages do
        delete 'comment_delete'
      end
      resources :project_documents
    end
    # resources :messages
    resources :contacts do
      delete 'remove_image'
      patch 'upload_image'
      get 'new_image'
      patch 'phone_update'
      get 'company_edit'
      patch 'company_update'
      collection do
        patch 'client_update/:id', to: 'contacts#client_update', as: 'client_update'
      end
    end
    resources :tickets do
      member do
        get 'overview'
      end
      resources :messages do
        get 'reply_edit'
        patch 'reply_update'
        delete 'reply_delete'
      end
      resources :ticket_documents
    end
    #resources :ticket_documents
    resources :invoices
    resources :inventories
    resources :messages
    resources :directories do
      collection do
        delete :destroy_all
        get 'system_files'
      end
    end
    resources :documents do
      collection do
        delete :destroy_all
        get 'upload_document'
        get 'update_documents'
        get 'selected_documents'
      end
    end
    post 'uploadfiles'=>'documents#upload'
  end

  get 'contacts/dashboard' => 'contacts/home#dashboard'

  get 'settings/index'
  post 'uploadfiles'=>'documents#upload'

  resources :leads do
    resources :comments, only: [:create, :update,:index]
    #resources :tasks
    collection do
      delete 'destroy_all'
      get 'import_leads'
      post 'import_map'
      get 'assign_all', to: 'leads#new_assign_all'
      post 'assign_all'
    end
    member do
      get 'convert_client'
      get 'edit_summary'
    end
  end
  post 'import_file' => 'leads#import_file'
  get 'import_form' => 'leads#import_form'
  resources :contacts do
    collection do
      get 'check_email'
      get 'resend_invitation'
      get 'lead_contacts'
      get 'client_contacts'
      get 'vendor_contacts'
      delete 'destroy_all'
    end
  end

  resources :project_tasks
  get 'search_auto_complete_data_tasks' => 'project_tasks#search_auto_complete_data_tasks', :as => "search_auto_complete_data_tasks"
  resources :projects do
    collection do
      delete 'destroy_all'
      get 'user_list'
      get 'list'
      post 'send_project_invitaiton'
      get 'project_user_list'
    end
    member do
      get 'overview'
      get 'invite_for_project'
      get 'project_details'
      get 'accept_user_invitation'
    end
    resources :messages do
      delete 'comment_delete'
    end
    resources :project_documents
  end

  get 'project_communication_dashborad' => 'projects#project_communication_dashborad', as: :project_communication_dashborad
  get "back_to_project/:id" => "projects#back_to_project", as: :back_to_project

  resources :messages
  resources :tickets do
    collection do
      delete 'destroy_all'
      get 'contacts_list'
      get 'user_list'
      get 'list'
      post 'send_ticket_invitaiton'
      get 'ticket_user_list'
      get 'reports'
      post 'download_attachment', to: 'tickets#download_attachment', as: :download_attachment
    end
    member do
      get 'overview'
      get 'invite_for_ticket'
      get 'ticket_details'
    end
    resources :messages do
      delete 'comment_delete'
      get 'reply_edit'
      patch 'reply_update'
      delete 'reply_delete'
    end
    resources :ticket_documents
  end

  get 'autocomplete_data' => 'tickets#autocomplete_data', :as => "autocomplete_data_tickets"
  get 'back_to_ticket/:id' => 'tickets#back_to_ticket', as: :back_to_ticket


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#dashboard'
  resources :settings do
    collection do
      get 'module', as: :module
      get 'actions'
      get 'users_settings', as: :users
      get 'module_select'
      get 'email'
      get 'revoke_mail_access'
      resources :users do
        delete 'remove_image'
        get 'signature'
        patch 'update_signature'
        patch 'upload_image'

        get 'resend_invitation'
      end
      get 'new_image' => 'users#new_image'
      resources :roles
    end
  end
  resources :groups do
    collection do
      get :change_position
    end
  end
  resources :fields do
    collection do
      get :change_position
      patch :change_position_in_table
      patch :change_header_view
      patch :toggle_visible_in_table
    end
    member do
      patch :change_properties
    end
  end
  resources :field_picklist_values do
    collection do
      get :change_klass
      get :change_field
      get :change_position
    end
  end
  resources :custom_values
  get '/dashboard', to: 'home#dashboard'

  resources :clients do
    resources :comments, only: [:create,:update,:index]
    resources :inventory_associations, module: :clients, only: [:index] do
      collection do
        get :subcategories
        get :inventory_groups
        get :inventory_group
        get :inventory_groups_by_sku
        get :bulk_new
        post :bulk_create
      end
    end
    resources :shipments, module: :clients, only: [:new, :create] do
      get 'package_label/:id', to: 'shipments#package_label', as: :package_label
    end
    resources :employees, module: :clients do
      member do
        get 'feedback'
      end
    end
    collection do
      delete :destroy_all
      get 'import_clients'
      post 'import_map'
      get 'select_client'
      get 'status_board'
      post 'update_status_board'
      get 'department_details'
      get :client_by_merchant_id
    end
    post 'set'
    member do
      get 'edit_summary'
      get 'send_menu_approval_email'
      get 'send_menu_approval_sms'
      get 'logs'
    end
  end
  post 'import_file_client' => 'clients#import_file_client'
  get 'import_form_client' => 'clients#import_form_client'

  resources :vendors do
    member do
      get 'edit_summary'
    end
    collection do
      delete :destroy_all
    end
  end


  get 'page1', to: 'home#page1'
  get 'project_communication_dashborad1', to: 'home#project_communication_dashborad1'
  resources :module_numbers
  get 'page2', to: 'home#page2'
  get "get_module_name" => "module_numbers#get_module_name"
  get 'privacy', to: 'home#privacy'
  get 'view_map', to: 'home#view_map'

  resources :invoices do
    collection do
      delete :destroy_all
      get :inventories
      get :clients
    end
    get 'email'
    post 'email_create'
    get 'preview'
    get 'download'
    resource :payment, except: [:edit, :update, :destroy]
  end

  resources :directories do
    collection do
      delete 'destroy_all'
      get 'system_files'
    end
  end
  resources :documents do
    collection do
      delete :destroy_all
      get 'upload_document'
      get 'update_documents'
      get 'selected_documents'
    end
  end

  resources :tasks do
    collection do
      delete :destroy_all
    end
    post :mark_as_completed
  end
  get 'back_to_task/:id', to: 'tasks#back_to_task', as: :back_to_task

  resources :notes do
    collection do
      delete :destroy_all
    end
  end
  get 'back_to_note/:id', to: "notes#back_to_note", as: :back_to_note
  resources :roles
  resources :emails do
    post :reply
    collection do
      get :sent
      get :draft
      get :connect
      get :update_draft
      get :create_draft
      delete 'destroy_draft/:id', to: 'emails#destroy_draft', as: 'destroy_draft'
    end
  end

  namespace :purchase_order do
    resources :devices, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :products, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :versions, only: [:show, :create]
  end

  resources :inventory_groups do
    collection do
      patch :setup_inventory_versions
      delete :destroy_all
      get :subcategories_for_category
    end
  end

  # Category Management
  resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :subcategories, only: [:new, :edit, :create, :update, :destroy]

  resources :inventories do
    collection do
      delete :destroy_all
      get :import
      post :import_map
      put :update_inventory_column
      get :subcategories_for_data_list
      post :import_file
    end
    member do
      get :logs
    end
  end

  resources :stock_adjustments, except: %i[index show]
  resources :email_templetes do
    collection do

app/models/field_picklist_value.rb
class FieldPicklistValue < ApplicationRecord
  audited

  default_scope { order(:position) }

  belongs_to :field

  before_update :update_records_to_new_value
  before_destroy :update_records_to_nil

  CLASS_MAP = {Lead => Client} # used to create same value in opposite model

  def create_value_in_opposite_class
    if FieldPicklistValue::CLASS_MAP[self.field.klass.constant] # create value in opposite model, see field_picklist_value.rb for more info
      klass = Klass.find_by(name: FieldPicklistValue::CLASS_MAP[self.field.klass.constant].name)
      field = klass.fields.find_by(name: self.field.name)
      return unless field
      field.field_picklist_values.create(value: self.value)
    end
  end

  private

  def update_records_to_new_value
    field.klass.constant.where(field.name => value_was).update_all(field.name => value) if value_changed?
  end

  def update_records_to_nil
    field.klass.constant.where(field.name => value).update_all(field.name => nil)
  end
end

app/controllers/field_picklist_values_controller.rb
class FieldPicklistValuesController < ApplicationController
  before_action :authenticate_user!

  def index
    @klasses = Klass.pluck(:label, :id)
    @field_names = []
    if params[:field_id].present?
      @field = Field.find(params[:field_id])
      @field_names = Field.where(klass_id: @field.klass_id, column_type: ["Picklist", "Multi-Select Check Box"],  have_custom_value: true).pluck(:label, :id)
      @field_picklist_values = @field.field_picklist_values
    end
  end

  def new
    @field_picklist_value = FieldPicklistValue.new(field_id: params[:field_id])
  end

  def create
    @field_picklist_value = FieldPicklistValue.new(field_picklist_value_params)
    if @field_picklist_value.save
      @field_picklist_value.create_value_in_opposite_class
      @field = @field_picklist_value.field
      @field_picklist_values = FieldPicklistValue.where(field: @field)
    end
  end

  def change_klass
    @klass = Klass.find(params[:klass_id])
  end

  def change_field
    @field = Klass.find(params[:klass_id]).fields.field_picklist_valuable.find_by(id: params[:field_id])
    @field_picklist_values = @field.field_picklist_values
  end

  def edit
    @field_picklist_value = FieldPicklistValue.find(params[:id])
  end

  def update
    @field_picklist_value = FieldPicklistValue.find(params[:id])
    if @field_picklist_value.update_attributes(field_picklist_value_params)
      @field = @field_picklist_value.field
      @field_picklist_values = FieldPicklistValue.where(field: @field)
    end
  end

  def destroy
    @field_picklist_value = FieldPicklistValue.find(params[:id])
    @field_picklist_value.destroy
    @field = @field_picklist_value.field
    @field_picklist_values = FieldPicklistValue.where(field: @field)
  end

  def change_position
    params[:field_picklist_value_ids].each_with_index do |field_picklist_value_id, position|
      FieldPicklistValue.find(field_picklist_value_id).update(position: position)
    end
  end

  private

  def field_picklist_value_params
    params.require(:field_picklist_value).permit(:field_id, :value, :color)
  end
end

app/helpers/field_picklist_values_helper.rb
module FieldPicklistValuesHelper
end

app/views/field_picklist_values/_form.html.erb
<div class="row">
  <div class='col-md-6'>
    <div class='form-group'>
      <%= f.label :value %>
      <%= f.text_field :value, class: 'form-control', required: true, disabled: f.object.is_system %>
    </div>
  </div>
  <div class='col-md-6'>
    <div class='form-group'>
      <%= f.label :color %>
      <%= f.color_field :color, class: 'form-control', disabled: f.object.is_system %>
    </div>
  </div>
  <%= f.hidden_field :field_id, value: f.object.field_id%>
</div>
<p>For color, you can choose from below according to it's status:</p>
<div class="row">
  <div class="col-sm-4">In Progress</div><div class="col-sm-4" style="background-color: #ff9029;">#ff9029</div>
</div>
<div class="row">
  <div class="col-sm-4">On Hold</div><div class="col-sm-4" style="background-color: #f01212">#f01212</div>
</div>
<div class="row">
  <div class="col-sm-4">Completed</div><div class="col-sm-4" style="background-color: #3cc87b">#3cc87b</div>
</div>

app/views/field_picklist_values/_modal.html.erb
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <%= form_for field_picklist_value, remote: true, class: "form-inline" do |f| %>

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Enter Value</h4>
        </div>
        <div class="modal-body">
          <%= render 'form', f: f %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/field_picklist_values/_picklist_value.html.erb
<div class="block-ui-box">
  <div class="row">
    <div class="col-md-12">
      <%= link_to new_field_picklist_value_path(field_id: field.id), remote:true, class: 'pull-right m-t-10 m-b-10 m-r-20' do%>
        Add Value <i class="fa fa-plus" aria-hidden="true"></i>
      <%end%>
    </div>
    <div class="col-md-12">
      <ul class="list-unstyled fields-sortable">
        <% field_picklist_values.each_with_index do |field_picklist_value, f_ind|%>
          <li class="block-ui-box m-t-5" data-field-picklist-value-id="<%= field_picklist_value.id %>">
            <%= field_picklist_value.value%>
            <% unless field_picklist_value.is_system %>
              <%= link_to field_picklist_value_path(field_picklist_value), method: :delete, remote: true do%>
              <i class="fa fa-trash pull-right" aria-hidden="true"></i>
              <% end %>
            <% end %>
            <%= link_to edit_field_picklist_value_path(field_picklist_value), remote: true do%>
              <i class="fa fa-pencil pull-right" aria-hidden="true"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<script>
  $(document).ready(function(){
    $( ".fields-sortable" ).sortable({
      stop: function(event, ui) {
        let fieldPicklistValueIds = $(this).sortable('toArray', {attribute: "data-field-picklist-value-id"});
        $.ajax({
          url: "<%= change_position_field_picklist_values_url %>",
          type: 'GET',
          data: {
            field_picklist_value_ids: fieldPicklistValueIds
          },
          dataType: "script"
        });
      }
    });
  });
</script>

app/views/field_picklist_values/_select_field.html.erb
<%= form_tag field_picklist_values_path, method: :post do %>
  <%= label_tag "Select Field","Select Field", class:'select-module-set'  %>
  <%= grouped_collection_select nil, :field_id, klass.groups, :field_picklist_valuable_fields, :label, :id, :label, {include_blank: "Select Field"}, class: 'form-control' %>
<%end%>
<script>
  $(document).ready(function(){
    $("#field_id").on('change', function(){
      $.ajax({
        url: "<%= change_field_field_picklist_values_url %>",
        type: 'GET',
        data: {
          klass_id: $("#klasses").val(),
          field_id: $(this).val()
        },
        dataType: "script",
        success: function(result){

        }
      });
    });
  });
</script>

app/views/field_picklist_values/change_field.js.erb
$("#picklist-values").html("<%= escape_javascript(render partial: 'picklist_value', locals: {field_picklist_values: @field_picklist_values, field: @field }) %>");

app/views/field_picklist_values/change_klass.js.erb
$("#select_field").html("<%= escape_javascript(render partial: 'select_field', locals: {klass: @klass}) %>");

app/views/field_picklist_values/create.js.erb
$("#picklist-values").html("<%= escape_javascript(render partial: 'picklist_value', locals: {field_picklist_values: @field_picklist_values, field: @field }) %>");
$('#myModal').modal('hide');

app/views/field_picklist_values/destroy.js.erb
$("#picklist-values").html("<%= escape_javascript(render partial: 'picklist_value', locals: { field_picklist_values: @field_picklist_values, field: @field }) %>")

app/views/field_picklist_values/edit.js.erb
$("#modal").html("<%= escape_javascript(render partial: 'modal', locals: {field_picklist_value: @field_picklist_value, klass: @klass}) %>")
$("#myModal").modal('show');

app/views/field_picklist_values/index.html.erb
<div class="site-main">
  <%= render 'layouts/sidebar'%>

  <div class="site-content">
    <div class="site-content-head">
      <div class="row">
        <div class="col-sm-12">
          <div class="l-menu">
            <%= link_to settings_path, class: "heading common-link"  do %> CRM Customization Settings <% end %>
            <span class="sub-menu-sitecontent m-x-10"> <i class="fa fa-angle-right"></i> </span>
            <span class="main-menu-sitecontent"> Picklist Value </span>
            <!-- <%= link_to field_picklist_values_path, class: "main-menu-sitecontent" do %> Picklist Value <% end %> -->
            <span class="sub-menu-sitecontent"></span>
          </div>
          <span class='pull-right'><a href="<%= settings_index_path %>" class='btn btn-success btn-sm back-btn-margin mt7'>Back</a></span>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-12">
        <%= form_tag field_picklist_values_path, method: :post, class: "form-inline" do %>
          <div class="site-content-data">
            <div class="block-ui-box-wrapper">
              <div  class="block-ui-box m-t-20">
                <div class='row'>
                  <div class="col-sm-12 text-center">
                    <div class="form-group mb10">
                    <%= label_tag "Select Module", "Select Module", class:'select-module-set' %>
                    <%= select_tag "klasses", options_for_select(@klasses, @field&.klass_id), { class: 'form-control', prompt: "Select Module"}%>
                    </div>
                  </div>
                </div>
                <div class='row'>
                  <div class="col-sm-12 text-center">
                   <div class='form-group mb10' id ='select_field'>
                   <%= label_tag "Select Field", "Select Field", class:'select-module-set'  %>
                    <%= select_tag "field_name", options_for_select(@field_names, @field&.id), { class: 'form-control', prompt: "Select Field"}%>
                  </div>
                </div>
              </div>
              </div>
            </div>
        <%end%>
    <div class='row'>
        <div class="col-md-12 m-t-30">
          <div class="block-ui-box-wrapper">
            <div id='picklist-values'>
              <%if @field_picklist_values.present? %>
                <%= render partial: 'picklist_value', locals: {field_picklist_values: @field_picklist_values, field: @field }%>
              <%end%>
            </div>
          </div>
        </div>

    </div>
  </div>
</div>
</div>
<div id='modal'></div>
<script>
  $(document).ready(function(){
    $("#klasses").on('change', function(){
      $.ajax({
        url: "<%= change_klass_field_picklist_values_url %>",
        type: 'GET',
        data: {
          klass_id: $(this).val()
        },
        dataType: "script",
        success: function(result){

        }
      });
    });



  });
</script>

app/views/field_picklist_values/new.js.erb
$("#modal").html("<%= escape_javascript(render partial: 'modal', locals: {field_picklist_value: @field_picklist_value, field_id: params[:field_id] }) %>")
$("#myModal").modal('show');

app/views/field_picklist_values/update.js.erb
$("#picklist-values").html("<%= escape_javascript(render partial: 'picklist_value', locals: {field_picklist_values: @field_picklist_values, field: @field }) %>");
$('#myModal').modal('hide');