config/routes.rb
Rails.application.routes.draw do

  # Devise Routes / Authentication routes
  devise_for :contacts, path: 'contact_users', controllers: { passwords: 'contacts/passwords', sessions: 'contacts/sessions' }
  devise_for :users, controllers: { registrations: 'registrations', passwords: 'passwords', sessions: 'users/sessions' }
  namespace :users do
    resource :two_factor_authentication, controller: 'two_factor_authentication', only: [:new, :show, :create] do
      collection do
        get :resend_direct_otp
      end
    end
  end
  namespace :users do
    resources :tfa_phone_numbers, only: [:index, :new, :create, :destroy]
  end


  # Engine Routes
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  mount Ckeditor::Engine => '/ckeditor'
  mount ActionCable.server => '/cable'

  # Application Routes
  get 'authorize' => 'auth#gettoken'
  get 'mail/index'

  get 'home/index'
  get 'google_autication' => 'google_imap#authentication'
  get 'oauth2callback' => 'google_imap#callback'
  get 'get_access_code' => 'google_imap#get_access_code'

  get 'home/dashboard'
  resources :work_flows do
    collection do
      post 'builder'
      post 'action_builder'
    end
  end
  resources :companies do
    get 'logo_image'
    delete 'remove_logo'
  end
  resources :search
  resources :user_permissions
  namespace :contacts do
    root 'home#dashboard'
    resources :projects do
      member do
        get 'overview'
        get 'accept_contact_invitation'
        get 'project_details'
      end
      collection do
      end
      resources :messages do
        delete 'comment_delete'
      end
      resources :project_documents
    end
    # resources :messages
    resources :contacts do
      delete 'remove_image'
      patch 'upload_image'
      get 'new_image'
      patch 'phone_update'
      get 'company_edit'
      patch 'company_update'
      collection do
        patch 'client_update/:id', to: 'contacts#client_update', as: 'client_update'
      end
    end
    resources :tickets do
      member do
        get 'overview'
      end
      resources :messages do
        get 'reply_edit'
        patch 'reply_update'
        delete 'reply_delete'
      end
      resources :ticket_documents
    end
    #resources :ticket_documents
    resources :invoices
    resources :inventories
    resources :messages
    resources :directories do
      collection do
        delete :destroy_all
        get 'system_files'
      end
    end
    resources :documents do
      collection do
        delete :destroy_all
        get 'upload_document'
        get 'update_documents'
        get 'selected_documents'
      end
    end
    post 'uploadfiles'=>'documents#upload'
  end

  get 'contacts/dashboard' => 'contacts/home#dashboard'

  get 'settings/index'
  post 'uploadfiles'=>'documents#upload'

  resources :leads do
    resources :comments, only: [:create, :update,:index]
    #resources :tasks
    collection do
      delete 'destroy_all'
      get 'import_leads'
      post 'import_map'
      get 'assign_all', to: 'leads#new_assign_all'
      post 'assign_all'
    end
    member do
      get 'convert_client'
      get 'edit_summary'
    end
  end
  post 'import_file' => 'leads#import_file'
  get 'import_form' => 'leads#import_form'
  resources :contacts do
    collection do
      get 'check_email'
      get 'resend_invitation'
      get 'lead_contacts'
      get 'client_contacts'
      get 'vendor_contacts'
      delete 'destroy_all'
    end
  end

  resources :project_tasks
  get 'search_auto_complete_data_tasks' => 'project_tasks#search_auto_complete_data_tasks', :as => "search_auto_complete_data_tasks"
  resources :projects do
    collection do
      delete 'destroy_all'
      get 'user_list'
      get 'list'
      post 'send_project_invitaiton'
      get 'project_user_list'
    end
    member do
      get 'overview'
      get 'invite_for_project'
      get 'project_details'
      get 'accept_user_invitation'
    end
    resources :messages do
      delete 'comment_delete'
    end
    resources :project_documents
  end

  get 'project_communication_dashborad' => 'projects#project_communication_dashborad', as: :project_communication_dashborad
  get "back_to_project/:id" => "projects#back_to_project", as: :back_to_project

  resources :messages
  resources :tickets do
    collection do
      delete 'destroy_all'
      get 'contacts_list'
      get 'user_list'
      get 'list'
      post 'send_ticket_invitaiton'
      get 'ticket_user_list'
      get 'reports'
      post 'download_attachment', to: 'tickets#download_attachment', as: :download_attachment
    end
    member do
      get 'overview'
      get 'invite_for_ticket'
      get 'ticket_details'
    end
    resources :messages do
      delete 'comment_delete'
      get 'reply_edit'
      patch 'reply_update'
      delete 'reply_delete'
    end
    resources :ticket_documents
  end

  get 'autocomplete_data' => 'tickets#autocomplete_data', :as => "autocomplete_data_tickets"
  get 'back_to_ticket/:id' => 'tickets#back_to_ticket', as: :back_to_ticket


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#dashboard'
  resources :settings do
    collection do
      get 'module', as: :module
      get 'actions'
      get 'users_settings', as: :users
      get 'module_select'
      get 'email'
      get 'revoke_mail_access'
      resources :users do
        delete 'remove_image'
        get 'signature'
        patch 'update_signature'
        patch 'upload_image'

        get 'resend_invitation'
      end
      get 'new_image' => 'users#new_image'
      resources :roles
    end
  end
  resources :groups do
    collection do
      get :change_position
    end
  end
  resources :fields do
    collection do
      get :change_position
      patch :change_position_in_table
      patch :change_header_view
      patch :toggle_visible_in_table
    end
    member do
      patch :change_properties
    end
  end
  resources :field_picklist_values do
    collection do
      get :change_klass
      get :change_field
      get :change_position
    end
  end
  resources :custom_values
  get '/dashboard', to: 'home#dashboard'

  resources :clients do
    resources :comments, only: [:create,:update,:index]
    resources :inventory_associations, module: :clients, only: [:index] do
      collection do
        get :subcategories
        get :inventory_groups
        get :inventory_group
        get :inventory_groups_by_sku
        get :bulk_new
        post :bulk_create
      end
    end
    resources :shipments, module: :clients, only: [:new, :create] do
      get 'package_label/:id', to: 'shipments#package_label', as: :package_label
    end
    resources :employees, module: :clients do
      member do
        get 'feedback'
      end
    end
    collection do
      delete :destroy_all
      get 'import_clients'
      post 'import_map'
      get 'select_client'
      get 'status_board'
      post 'update_status_board'
      get 'department_details'
      get :client_by_merchant_id
    end
    post 'set'
    member do
      get 'edit_summary'
      get 'send_menu_approval_email'
      get 'send_menu_approval_sms'
      get 'logs'
    end
  end
  post 'import_file_client' => 'clients#import_file_client'
  get 'import_form_client' => 'clients#import_form_client'

  resources :vendors do
    member do
      get 'edit_summary'
    end
    collection do
      delete :destroy_all
    end
  end


  get 'page1', to: 'home#page1'
  get 'project_communication_dashborad1', to: 'home#project_communication_dashborad1'
  resources :module_numbers
  get 'page2', to: 'home#page2'
  get "get_module_name" => "module_numbers#get_module_name"
  get 'privacy', to: 'home#privacy'
  get 'view_map', to: 'home#view_map'

  resources :invoices do
    collection do
      delete :destroy_all
      get :inventories
      get :clients
    end
    get 'email'
    post 'email_create'
    get 'preview'
    get 'download'
    resource :payment, except: [:edit, :update, :destroy]
  end

  resources :directories do
    collection do
      delete 'destroy_all'
      get 'system_files'
    end
  end
  resources :documents do
    collection do
      delete :destroy_all
      get 'upload_document'
      get 'update_documents'
      get 'selected_documents'
    end
  end

  resources :tasks do
    collection do
      delete :destroy_all
    end
    post :mark_as_completed
  end
  get 'back_to_task/:id', to: 'tasks#back_to_task', as: :back_to_task

  resources :notes do
    collection do
      delete :destroy_all
    end
  end
  get 'back_to_note/:id', to: "notes#back_to_note", as: :back_to_note
  resources :roles
  resources :emails do
    post :reply
    collection do
      get :sent
      get :draft
      get :connect
      get :update_draft
      get :create_draft
      delete 'destroy_draft/:id', to: 'emails#destroy_draft', as: 'destroy_draft'
    end
  end

  namespace :purchase_order do
    resources :devices, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :products, only: [:index, :new, :edit, :create, :update, :destroy]
    resources :versions, only: [:show, :create]
  end

  resources :inventory_groups do
    collection do
      patch :setup_inventory_versions
      delete :destroy_all
      get :subcategories_for_category
    end
  end

  # Category Management
  resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :subcategories, only: [:new, :edit, :create, :update, :destroy]

  resources :inventories do
    collection do
      delete :destroy_all
      get :import
      post :import_map
      put :update_inventory_column
      get :subcategories_for_data_list
      post :import_file
    end
    member do
      get :logs
    end
  end

  resources :stock_adjustments, except: %i[index show]
  resources :email_templetes do
    collection do

app/controllers/contacts/home_controller.rb
include Geokit::Geocoders

class Contacts::HomeController < ApplicationController
  layout 'contacts'
  before_action :authenticate_contact!
  include AuthHelper

  def dashboard
    @project_unread_count = current_contact.unreads.where(unreadable_type: 'Project').count
    @project_count = current_contact.projects.count
    @invoice_unread_count = current_contact.unreads.where(unreadable_type: 'Invoice').count
    @invoice_count = current_contact.lead_client_contact.contactable.invoices.count
    @ticket_unread_count = current_contact.unreads.where(unreadable_type: 'Ticket').count
    @ticket_count = current_contact.associated_tickets.count
  end

  def view_map
    # render layout: false
    coords = MultiGeocoder.geocode(params[:address])
    @lat = coords.lat
    @long = coords.lng

  end

  def page1

  end

  def project_communication_dashborad1
  end
end

app/controllers/home_controller.rb
include Geokit::Geocoders

class HomeController < ApplicationController
  before_action :authenticate_user!
  include AuthHelper

  def dashboard
    if current_user.role.try(:name) == 'Sales'
      merchant_ids = current_user.clients.pluck(:nab_merchant_id_mid_).reject(&:blank?)
      begin
        resp = Faraday.post("http://#{amount_collection_host}/api/v1/locations_amount_collections/amount_collection") do |req|
          req.headers['accept'] = 'application/json'
          req.body = { 'locations_amount_collection': { 'merchant_ids': merchant_ids } }
        end
        response_body = JSON.parse(resp.body)
        @chart_data = response_body['data']['date_wise_amount_collection']&.sort
        @last_month_amount_collection = response_body['data']['last_month_amount_collection']
        @last_30_days_amount_collection = response_body['data']['last_30_days_amount_collection']
        @amount_by_merchant_id = response_body['data']['location_merchant_amount']
      rescue
        @error = "Parent Host didn't respond properly."
      end
      @last_month = Date::MONTHNAMES[(Date.today - 1.month).month]
      @start_date = (Date.today - 31).strftime
      @end_date = (Date.today - 1).strftime
      @today = Date.today.strftime
      @clients = current_user.clients
      @deployments = current_user.meetings.last_30_days
      @tickets = current_user.owned_tickets.last_30_days
      # @deployments = current_user.meetings.where('start_time > ?', 31.days.ago)
    else 
      @project_unread_count = current_user.unreads.where(unreadable_type: 'Project').count
      @project_count = current_user.has_role?(:super_admin) ? Project.count : current_user.projects.count
      # TODO: implement invoice_unread_count
      @invoice_count = Invoice.count
      @owned_tickets_count = current_user.owned_tickets.count
      @associated_tickets_count = current_user.associated_tickets.count
      @lead_contact =  LeadClientContact.where(contactable_type: "Lead").count
      @lead_count = Lead.count
      @client_contact = LeadClientContact.where(contactable_type: "Client").count
      @client_count = Client.count
      @task_count = Task.count
      @inventory_count = InventoryGroup.count
      @help_desk_count = HelpDesk.count
      @contract_count = Contract::Contract.count
    end
  end

  def view_map
    # render layout: false
    coords = MultiGeocoder.geocode(params[:address])
    @lat = coords.lat
    @long = coords.lng
  end

  def page1
  end

  def privacy
  end

  def project_communication_dashborad1
  end

  private

  def amount_collection_host
    Rails.env.development? ? 'goipos.net' : 'goipos.net'
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def account_status_color(status)
    if status == 'Actively Processing' || status == 'Production Mode' || status == 'Active - not processing'
      'bg-lightgreen'
    elsif status == 'Account on HOLD' || status == 'In Progress'
      'bg-yellow'
    elsif status == 'Account Cancelled' || status == 'Closed by iPos' || status == 'Closed by Client'
      'bg-lightred'
    end
  end
end

app/views/home/_dashboard_menu.html.erb
<div class="row dashboard_page">
  <div class="col-sm-12">
    <div class="setting-icon-wrapper">
      <div class="d-flex row">

        <% if checked_permission?(current_user, @klass_list["Lead"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to leads_path do  %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon1.png') %>
              <div class="badge badge-count blue_badge"><%= @lead_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Lead <br />Company</p>
              </div>
              <div class="text-right">
                <%= image_tag asset_path('arrow.png'), class: 'arrow' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>

        <% if checked_permission?(current_user, @klass_list["Contact"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to lead_contacts_contacts_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon2.png') %>
              <div class="badge badge-count blue_badge"><%= @lead_contact %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Lead <br />Contact</p>
              </div>
              <div class="text-right">
                <%= image_tag asset_path('arrow.png'), class: 'arrow' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>

        <% if checked_permission?(current_user, @klass_list["Client"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to clients_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon3.png') %>
              <div class="badge badge-count blue_badge"><%= @client_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Client <br />Company</p>
              </div>
              <div class="text-right">
                <%= image_tag asset_path('arrow.png'), class: 'arrow' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>


        <% if checked_permission?(current_user, @klass_list["Contact"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to client_contacts_contacts_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon4.png') %>
              <div class="badge badge-count blue_badge"><%= @client_contact %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Client <br />Contact</p>
              </div>
              <div class="text-right">
                <%= image_tag asset_path('arrow.png'), class: 'arrow' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>

        <% if checked_permission?(current_user, @klass_list["Client"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to status_board_clients_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon5.png') %>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Production <br />Summary</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>


        <% if checked_permission?(current_user, @klass_list["Task"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to tasks_path  do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon6.png') %>
              <div class="badge badge-count blue_badge"><%= @task_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Tasks</p>
              </div>
              <div class="text-right">
                <%= image_tag asset_path('arrow.png'), class: 'arrow' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>


        <% if checked_permission?(current_user, @klass_list["Ticket"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to tickets_path  do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon7.png') %>
              <div class="badge badge-count red_badge"><%= @associated_tickets_count %></div>
              <div class="badge badge-count blue_badge"><%= @owned_tickets_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Tickets</p>
              </div>
              <div class="text-right">
                <%= image_tag asset_path('arrow.png'), class: 'arrow' %>
              </div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>

        <% if checked_permission?(current_user, @klass_list[ProjectManagement::Project.klass_name], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to project_management_projects_path  do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon8.png') %>
              <div class="badge badge-count red_badge"><%= @project_unread_count %></div>
              <div class="badge badge-count blue_badge"><%= @project_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Projects</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>

        <% if checked_permission?(current_user, @klass_list["Invoice"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
        <%= link_to invoices_path do %>
            <div class="setting-icon">
              <div class="setting-icon-main">
                <%= image_tag asset_path('icon9.png') %>
                <div class="badge badge-count blue_badge"><%= @invoice_count %></div>


                <div class="setting-icon-title mb-0">
                  <p class="fw-600 fs-14">Invoice </p>
                </div>
                <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
              </div>
            </div>
            <% end %>
        </div>
        <% end %>

        <% if checked_permission?(current_user, @klass_list["Inventory"], @action_list["read"]) %>
        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to inventory_groups_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon10.png') %>
              <div class="badge badge-count blue_badge"><%= @inventory_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Inventories </p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>
        <% end %>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to help_desks_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon11.png') %>
              <div class="badge badge-count blue_badge"><%= @help_desk_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14">Help <br />Desk</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to contract_contracts_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon12.png') %>
              <div class="badge badge-count blue_badge"><%= @contract_count %></div>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14"> Lead/Client <br />Contacts</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to kpis_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon13.png') %>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14"> KPI</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to calendar_meetings_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon14.png') %>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14"> Deployment <br />Calendar</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to reports_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">

              <%= image_tag asset_path('icon15.png') %>

              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14"> Reports</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to time_sheet_logs_all_users_users_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon16.png') %>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14"> User <br />Timesheet</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6">
          <%= link_to settings_path do %>
          <div class="setting-icon">
            <div class="setting-icon-main">
              <%= image_tag asset_path('icon17.png') %>
              <div class="setting-icon-title mb-0">
                <p class="fw-600 fs-14"> CRM <br />Settings</p>
              </div>
              <div class="text-right"> <%= image_tag asset_path('arrow.png'), class: 'arrow' %></div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .dashboard_page .setting-icon-main {
    width: 100%;
    height: auto;
    padding: 15px 10px;
    display: block;
    text-align: left;
    min-height: 174px;
    margin-bottom: 20px;
  }

  .setting-icon {
    margin-right: unset;
  }

  .dashboard_page .setting-icon-wrapper {
    padding-left: 0;
    padding-right: 0;
  }

  .dashboard_page .badge-count {
    float: right;
    border-radius: 50%;
    position: unset;
  }

  .dashboard_page .setting-icon-title {
    margin-bottom: 0;
  }

  .dashboard_page .blue_badge {
    background-color: #007aff;
  }

  .dashboard_page .red_badge {
    background-color: #fe2d55;
    margin-left: 5px;
  }

  .dashboard_page .setting-icon p {
    max-width: 102px;
    margin-bottom: 0px;
    min-height: 33px;
  }

  .dashboard_page .setting-icon-main {
    box-shadow: unset;
    border: 1px solid #f1f1f1;
    border-radius: 12px;
  }

  .dashboard_page .setting-icon-main:hover {
    box-shadow: 0px 0px 7px 0px rgb(105 105 105 / 20%);
  }

  .dashboard_page .arrow {
    opacity: 0.65;
  }

  .dashboard_page .setting-icon-main:hover .arrow {
    opacity: 1;
  }

  .dashboard_page .setting-icon-wrapper {
    display: unset;
  }
</style>

app/views/home/_map.html.erb
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Map</h4>
      </div>
      <div class="modal-body">
        <div id='address_map'></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
function initMap() {
  // The location of Uluru
  var uluru = {lat: parseFloat(<%= lat %>), lng: parseFloat(<%= long %>)};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('address_map'), {zoom: 17, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map,icon: {
      url: "http://maps.google.com/mapfiles/ms/icons/red-dot.png",
      labelOrigin: new google.maps.Point(75, 32),
      size: new google.maps.Size(32,32),
      anchor: new google.maps.Point(16,32)
      },
      label: {
        text: "<%= params[:address]%>",
        color: "#C70E20",
        fontWeight: "bold"
      }});
}
</script>

app/views/home/dashboard.html.erb
<div class="site-main">
  <%= render 'layouts/sidebar'%>
  <div class="site-content">
    <div class="dynmic-tab-div">
      <div class="row dashboard-page">
        <div class="col-sm-12">
          <div class="dynmic-tab-div-header">
            <div class="heading dashboard_toggle cursor-pointer">DASHBOARD</div>
            <% if current_user.role.try(:name) == 'Sales' %>
              <div class="heading merchant_toggle cursor-pointer">MERCHANTS</div>
            <% end %>
          </div>
          <div class="dynmic-tab-div-data">
            <% if current_user.role.try(:name) == 'Sales' %>
              <%= render partial: 'sales_dashboard' %>
            <% else %>
              <%= render partial: 'dashboard_menu' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .cursor-pointer{cursor: pointer;}
  .active{border-bottom: 2px solid;}
</style>

app/views/home/privacy.html.erb
<p> All of the data that is provided by you is secured.</p>